#' Convert a volume tree to a data.frame
#'
#' Extract the name, label, and volumes for each node of the
#' tree. The volumes are then expanded out creating a
#' `data_frame` with n x v rows where n is the number of
#' rows and v is the number of volumes
#' @param vol_tree The volume tree of interest
#' @param filterFun which nodes to include in the tree, defaults
#' to isLeaf, all can be included with `function(n) TRUE`
#' @return A `data_frame` with the volume tree
#' @md
#' @export
tree_to_volume_frame <-
  function(vol_tree, filterFun = isLeaf){
    max_depth <-
      vol_tree$Get("level") %>%
      max
    
    parents <-
      rep("", max_depth) %>%
      setNames(paste0("level", seq_len(max_depth))) %>%
      as.list %>%
      (dplyr::as_data_frame)
    
    vf <-
      vol_tree$Get(filterFun = filterFun
                 , function(node){
                   node_attrs <-
                     data_frame(name = node$name
                              , volume = list(as.numeric(node$volumes))
                              , ind = list(as.character(1:length(node$volumes)))
                              , is_leaf = isLeaf(node))

                   depth <- node$level
                   node_path <- parents
                   node_path[,seq_len(depth)] <- node$path

                   cbind(node_attrs, node_path)
                 }
               , simplify = FALSE) %>%
      bind_rows %>%
      unnest

    vf
  }

#' Associate metadata with a volume tree frame
#'
#' Take a volume tree frame generated by [tree_to_volume_frame]
#' and associated metadata. The rows of metadata should correspond
#' to the order of the volumes in the original volume tree.
#'
#' @param vol_frame the volume frame
#' @param metadata the metadata frame
#' @return the tagged data frame
#' @export
tag_volume_frame <-
  function(vol_frame, metadata){
    metadata_munged <-
      metadata %>% mutate(ind = seq_len(n()))


    inner_join(vol_frame, metadata, by = "ind") %>%
      group_by(name) %>%
      mutate(scaled_vol = as.numeric(scale(volume))) %>%
      ungroup
  }


